
###

@KickStartApi_HostAddress = https://localhost:7224

GET {{KickStartApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{KickStartApi_HostAddress}}/api/Authentication/token
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}
> {% client.global.set("auth_token", response.body.token); %}

###

GET {{KickStartApi_HostAddress}}/Sites
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{KickStartApi_HostAddress}}/Sites/GetSite
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{KickStartApi_HostAddress}}/api/Demos
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{KickStartApi_HostAddress}}/api/Demos/Id/3
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{KickStartApi_HostAddress}}/api/Demos
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Demo 1",
  "description": "This is a demo",
  "isActive": true
}

###

PUT {{KickStartApi_HostAddress}}/api/Demos/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 3,
  "name": "Demo 1 Updated",
  "description": "This is a demo updated"
}

###

PATCH {{KickStartApi_HostAddress}}/api/Demos/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 3,
  "description": "This is a patched demo"
}

###

DELETE {{KickStartApi_HostAddress}}/api/Demos/3
Accept: application/json
Authorization: Bearer {{auth_token}}

###
