@WebApi_HostAddress = https://localhost:7270

###

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/Authentication/token
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}
> {% client.global.set("auth_token", response.body.token); %}

###

GET {{WebApi_HostAddress}}/Sites
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{WebApi_HostAddress}}/Sites/GetSite
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{WebApi_HostAddress}}/api/Demos
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{WebApi_HostAddress}}/api/Demos/Id/3
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{WebApi_HostAddress}}/api/Demos
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Demo 1",
  "description": "This is a demo",
  "isActive": true
}

###

PUT {{WebApi_HostAddress}}/api/Demos/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 3,
  "name": "Demo 1 Updated",
  "description": "This is a demo updated"
}

###

PATCH {{WebApi_HostAddress}}/api/Demos/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 3,
  "description": "This is a patched demo"
}

###

DELETE {{WebApi_HostAddress}}/api/Demos/3
Accept: application/json
Authorization: Bearer {{auth_token}}

###
