# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Solution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore NuGet Packages
        run: dotnet restore net9/KickstartApp/KickstartApp.sln

      - name: Build Solution
        run: dotnet build net9/KickstartApp/KickstartApp.sln --no-restore

      - name: Run Tests
        run: dotnet test net9/KickstartApp/KickstartApp.sln --no-build --verbosity normal
