name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    env:
      TEST_PROJECT_FILE: test/UnitTests/UnitTests.csproj
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Restore SigningKey
        run: echo "${{ secrets.STRONG_NAME_KEY_B64 }}" | base64 -d > DhKey.snk

      - name: Build solution
        run: dotnet build --configuration Debug --no-incremental

      - name: Run Unit Tests
        working-directory: ${{ github.workspace }}
        run: dotnet test $TEST_PROJECT_FILE --no-build --logger "trx;logFileName=tests_results.trx" /p:CollectCoverage=true /p:CoverletOutput=.qodana/code-coverage/ /p:CoverletOutputFormat=lcov

      - name: List all coverage.json files with full path
        run: find ${{ github.workspace }} -type f -name '*coverage*'

      - name: Archive coverage data for Qodana
        uses: actions/upload-artifact@v4
        with:
          name: coverage.json
          path: .qodana/code-coverage
          overwrite: true

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
          args: '--solution=WebKickStartApp.sln'
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1670587391 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
          
      - name: Clean up Signing Key
        if: always()
        run: rm -f DhKey.snk
