name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Restore SigningKey
        run: echo "${{ secrets.STRONG_NAME_KEY_B64 }}" | base64 -d > DhKey.snk

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1.1
        with:
          pr-mode: false
          args: '--solution=WebKickStartApp.sln'
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1670587391 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
          
      - name: Clean up Signing Key
        if: always()
        run: rm -f DhKey.snk
